### ISSUE TITLE
[rush] Incremental build reports InternalError for packages with optional peer dependencies

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#1621]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

In PR https://github.com/microsoft/rushstack/pull/1618 we introduced the ability to disable implicit preferred versions, by setting `implicitlyPreferredVersions=false`.  This eliminates certain installation errors, and it will default to being enabled for PNPM 4.x.

However, the Azure SDK reported an InternalError that occurs due to a bug in the improved incremental build logic that was recently introduced by PR https://github.com/microsoft/rushstack/pull/1526.

@mikeharder provided this repro:

```
git clone https://github.com/mikeharder/azure-sdk-for-js
git checkout f1a8795ea18fc5d4f2112838c82821f48b100695
rush update update --full
```

`rush link` fails with this callstack:

```
Error: Internal Error: Could not find peer dependency 'typescript' that satisfies version '*'

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
    at PnpmProjectDependencyManifest._addDependencyInternal (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmProjectDependencyManifest.js:117:31)
    at PnpmProjectDependencyManifest._addDependencyInternal (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmProjectDependencyManifest.js:74:22)
    at PnpmProjectDependencyManifest._addDependencyInternal (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmProjectDependencyManifest.js:74:22)
    at PnpmProjectDependencyManifest.addDependency (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmProjectDependencyManifest.js:33:14)
    at PnpmLinkManager._createLocalPackageForDependency (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmLinkManager.js:231:43)
    at PnpmLinkManager._linkProject (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmLinkManager.js:156:42)
    at promise.then (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmLinkManager.js:39:33)
```

Setting `"legacyIncrementalBuildDependencyDetection": true` in `experiments.json` eliminates the error.  But obviously that's not the solution we want.

## Details

The new incremental link logic is trying to crawl the dependencies of the `@rush-temp/abort-controller` project in order to collect the `shrinkwrap-deps.json` inventory.

It follows `@typescript-eslint/eslint-plugin`...
```yaml
  'file:projects/abort-controller.tgz':
    dependencies:
      '@typescript-eslint/eslint-plugin': 2.6.1_f826f0ccb5c1fa5c7ef10e2b959e7a19
```
...to `@typescript-eslint/experimental-utils`...
```yaml
  /@typescript-eslint/eslint-plugin/2.6.1_f826f0ccb5c1fa5c7ef10e2b959e7a19:
    dependencies:
      '@typescript-eslint/experimental-utils': 2.6.1_eslint@6.6.0+typescript@3.6.4
```
...to `@typescript-eslint/typescript-estree`...
```yaml
  /@typescript-eslint/experimental-utils/2.6.1_eslint@6.6.0+typescript@3.6.4:
    dependencies:
      '@typescript-eslint/typescript-estree': 2.6.1_typescript@3.6.4
```
...which looks like this:
```yaml
  /@typescript-eslint/typescript-estree/2.6.1_typescript@3.6.4:
    dependencies:
      debug: 4.1.1
      glob: 7.1.6
      is-glob: 4.0.1
      lodash.unescape: 4.0.1
      semver: 6.3.0
      tsutils: 3.17.1_typescript@3.6.4
    dev: false
    engines:
      node: ^8.10.0 || ^10.13.0 || >=11.10.1
    peerDependencies:
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
```

[This code](https://github.com/microsoft/rushstack/blob/927c1d99cc7bd15bc41c92bfd07fa62127027dd6/apps/rush-lib/src/logic/pnpm/PnpmProjectDependencyManifest.ts#L152) in PnpmProjectDependencyManifest.ts fails to find the `typescript: '*'` peer dependency.

**Comment by octogonz** [comment]
I noticed this entry:
```yaml
peerDependenciesMeta:
  typescript:
    optional: true
```

Looks like 25 days ago PR https://github.com/typescript-eslint/typescript-eslint/pull/990 converted TypeScript to be an "optional peer dependency".  This is a relatively new package manager feature that we need to check for.
