### ISSUE TITLE
[api-extractor] Treat keyword-types as something like references in excerpts

### ISSUE THREAD

**Issue by rbuckton** [microsoft/rushstack#1806]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

api-extractor treats keyword-types like `string` or `number` aren't distinguished from other tokens in an excerpt like references are, so they aren't included in the `references:` list in the .yml output. This is unfortunate as it prevents them from being hyperlinked in docfx when using an `xrefmap.yml` file that specifies the references to these types.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Run api-extractor/api-documenter against a sample such as this:

```ts
export function foo(): number;
export function bar(): string | number;
```

Next, create an `xrefmap.yml` file:

```yml
### YamlMime:XRefMap
sorted: false
references:
- uid: number
  name: number
  fullName: number
  href: https://tc39.github.io/ecma262/#sec-number-objects
- uid: string
  name: string
  fullName: string
  href: https://tc39.github.io/ecma262/#sec-string-objects
```

Next, create a `docfx.json` file with the following:

```json
{
  "build": {
  "content": [
    { "files": ["**/*.yml"], "src": "path/to/api-documenter/yml", "dest": "api" }
  ],
  "xref": [
    "path/to/xrefmap.yml"
  ],
  "dest": "out"
}
```

Finally, in the directory where `docfx.json` resides execute `docfx --serve` and open the documentation website (usually `http://localhost:8080`). If you navigate to the html file for the generated documentation the type for `number` and `string | number` will not be hyperlinked.

**What is the expected behavior?**

Primitive types like `string`, `symbol`, `number`, `bigint`, `boolean`, `null`, `undefined`, `object`, etc. should be treated as something like a reference excerpt so that api-documenter can add an entry for them to the `references:` list in the output yaml file, similar to this:

```yaml
### YamlMime:UniversalReference
items:
  ...
references:
- uid: number
- uid: string
- uid: '@foo!bar~0:complex`
  name: string | number
  fullName: string | number
  spec.typeScript:
  - uid: string
  - name: ' | '
    fullName: ' | '
  - uid: number
```

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** api-extractor (and api-documenter)
* **Tool Version:** 7.7.12
* **Node Version:** 13.0.1
  * **Is this a LTS version?** no
  * **Have you tested on a LTS version?** yes
* **OS:** Windows 10 Enterprise
