### ISSUE TITLE
[api-documenter] markdown-style xref links in yaml output should be url encoded.

### ISSUE THREAD

**Issue by rbuckton** [microsoft/rushstack#1840]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

In the yaml output, markdown links generated from `{@link}` tags should be properly encoded as the `#` character is treated as a the hash part of a URL:

**index.d.ts**
```ts
export declare class C {
  x: number;
  /** {@link C.x} */
  bar(): void;
}
```

**index.yml**
```yml
- uid: 'mypackage!C#bar:method'
  summary: >-
    [C.x](xref:mypackage!C#x:member)
```

**DocFX output**
```
Build succeeded with warning.
[20-04-22 01:14:24.231]Warning:[BuildCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.Apply Templates](path/to/index.yml)1 invalid cross reference(s) "[C.x](xref:mypackage!C#x:member)".
        1 Warning(s)
        0 Error(s)
```

**What is the expected behavior?**

The link in *index.yml* should be passed through `encodeURIComponent`:

**index.yml**
```yml
- uid: 'mypackage!C#bar:method'
  summary: >-
    [C.x](xref:mypackage!C%23x:member)
```

* **Tool:** api-documenter
* **Tool Version:** 7.7.18
* **Node Version:** 10.17.0
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** Windows 10
