### ISSUE TITLE
Expose DAG functionality

### ISSUE THREAD

**Issue by dfee** [microsoft/rushstack#1857]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**
`rush change` along with `rush build` and other commands build and navigate a DAG. This DAG would be very useful for CI and analysis.

I'm unsure of the best format for exposing this information, but it could be either via command-line or in a file managed by Rush.

If this DAG is flattened (which is fine) there are two highly relevant features that would be helpful:
1. upstream dependencies of the package
2. downstream dependents of the package

here is a yaml example (though it doesn't /need/ to be in yaml):
```yaml
---
packages:
  "@mono/package-a":
    dependencies: []
    dependents:
      - "@mono/package-b"
      - "@mono/package-c"
  "@mono/package-b":
    dependencies:
      - "@mono/package-b"
    dependents:
      - "@mono/package-c"
  "@mono/package-c":
    dependencies:
      - "@mono/package-a"
      - "@mono/package-b"
    dependents:
      - "@mono/package-d"
  "@mono/package-d":
    dependencies:
      - "@mono/package-c"
    dependents: []
```

Notice in the case of `@mono/package-d`:
- we're not requiring that `@mono/package-a` report grandchildren as dependencies
- we're not requiring that it reports grandparent dependents.

This should be enough for us to "walk" the dependencies programmatically.

In addition, if there was an option to list those packages that have changed (e.g. `rush change --list`) then that would be helpful for informing the CI of which packages need to be tested when branches are pushed. Note, this is in addition to the DAG description above, but is the most immediate use-case.
