### ISSUE TITLE
[rush] Enable Azure Pipeline Caching of pnpm packages?

### ISSUE THREAD

**Issue by AndrewCraswell** [microsoft/rushstack#2253]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

Apologies if this is not the right venue for this question -- I didn't see a tag for questions so feel free to close if I should ask somewhere else. I'm trying to use Azure Pipeline Caching and I've nearly got something work with the following template:

```yml
steps:
  - task: Cache@2
    inputs:
      key: '"pnpm-store" | "$(Agent.OS)" | common/config/rush/pnpm-lock.yaml'
      restoreKeys: |
        "pnpm-store" | "$(Agent.OS)"
        "pnpm-store"
      path: common/temp/pnpm-store
      cacheHitVar: CACHE_RESTORED
    displayName: Cache pnpm

  - script: 'node common/scripts/install-run-rush.js install'
    condition: ne(variables.CACHE_RESTORED, 'true')
    displayName: 'Rush Install'
```

This works, but subsequent Rush commands will fail because without executing the `rush install` command, the `common/temp` folder seems to not be created. Is there a good way to force the temp folder to be created without doing an install, so that in the cache where the packages can be restored from cache I can still ensure the temp folder exists?
