### ISSUE TITLE
[api-documenter] Generating with "yaml" option includes Sharepoint reference

### ISSUE THREAD

**Issue by NickHeiner** [microsoft/rushstack#2452]
## Summary

When I run `api-documenter yaml`, I get the following output in `toc.yml`:

```yml
items:
  - name: SharePoint Framework reference
    href: ~/overview/sharepoint.md
    items:
      - name: jscodemod
        uid: '@nth/jscodemod!'
```

This appears to come from [this code snippet](https://github.com/microsoft/rushstack/blob/f9ad7633a9deacf8004ae559794ae81336bf02c0/apps/api-documenter/src/documenters/YamlDocumenter.ts#L123-L129).

I think this is just a mistake where default filler text is being included; I'm not doing anything with Sharepoint. 😄 

## Repro steps

I'm pretty sure this will repro anywhere, but I'm specifically seeing it [at this commit in this repo](https://github.com/NickHeiner/jscodemod/tree/ca41e14a11ae8ef7c3d25f45a8dc72b0881f8276). Just run `yarn && yarn build-api-docs`.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-documenter` version? | `7.12.6` |
| Operating system? | Mac |
| Documentation target? | YAML |
| Would you consider contributing a PR? | Sorry, I don't have time. |
| TypeScript compiler version? | Whatever version of TS `@microsoft/api-extractor@7.13.0` uses :smile: |
| Node.js version (`node -v`)? | `12.14.0` |
