### ISSUE TITLE
[api-documenter] Nested namespaces are no longer shown in the TOC yml output

### ISSUE THREAD

**Issue by AlexJerabek** [microsoft/rushstack#2564]
## Summary

Nested namespaces become hidden in the yml output. As shown in the below example, neither the name nor the yml hierarchy reflect the inner namespace. Only the UIDs have the namespace in them, but this isn't visible in the TOC. The end result for consumers of our documentation is what appears to be an unalphabetized list.

This behavior did not exist in api-documenter 7.5.0. In that version, nested namespaces ended up as expected in the yml.

## Repro steps

  **Expected result:** 
**Previous**:
```
              - name: Addin
                uid: 'office!Office.Addin:interface'
              - name: AddinCommands
                items:
                  - name: Event
                    uid: 'office!Office.AddinCommands.Event:interface'
                  - name: EventCompletedOptions
                    uid: >-
                      office!Office.AddinCommands.EventCompletedOptions:interface
                  - name: Source
                    uid: 'office!Office.AddinCommands.Source:interface'
              - name: AsyncContextOptions
                uid: 'office!Office.AsyncContextOptions:interface'
```
  **Actual result:** 
**Current**:
```
          - name: Addin
            uid: 'office!Office.Addin:interface'
          - name: Event
            uid: 'office!Office.AddinCommands.Event:interface'
          - name: EventCompletedOptions
            uid: 'office!Office.AddinCommands.EventCompletedOptions:interface'
          - name: Source
            uid: 'office!Office.AddinCommands.Source:interface'
          - name: AsyncContextOptions
            uid: 'office!Office.AsyncContextOptions:interface'
```
## Details

**.Minimum d.ts file sample**:
```
namespace Office {
    namespace AddinCommands {
        interface Event {
        }
    }
}

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-documenter` version? | 7.12.14|
| Operating system? | Windows  |
| Documentation target? | DocFX (YAML) |
| Would you consider contributing a PR? |  No |
| TypeScript compiler version? | 4.1.5 |
| Node.js version (`node -v`)? | 12.16.1 |
