### ISSUE TITLE
[api-documenter] Support for TypeAlias in YamlDocumenter

### ISSUE THREAD

**Issue by AlexJerabek** [microsoft/rushstack#2567]
## Summary

In `api-documenter-test`, there's a type alias in the test `api-documenter-test.api.json`:
```
{
          "kind": "TypeAlias",
          "canonicalReference": "api-documenter-test!TypeAlias:type",
...
```

References to this type alias are pulled in by the API Documenter, but the actual type alias itself is never declared. The only references to the type alias's UID are in functions using it, as shown in this sample from `api-documenter-test.yml`:

```
syntax:
      content: 'export declare function exampleFunction(x: ExampleTypeAlias, y: number): IDocInterface1;'
      parameters:
        - id: x
          description: an API item that should get hyperlinked
          type: '<xref uid="api-documenter-test!ExampleTypeAlias:type" />'
        - id: 'y'
          description: a system type that should NOT get hyperlinked
          type: number
      return:
        type: '<xref uid="api-documenter-test!IDocInterface1:interface" />'
        description: an interface that should get hyperlinked
```

While the description claims that `ExampleTypeAlias` should be hyperlinked to, there's no source that a hyperlink could link to.

## Details

In my mind, there are two output solutions: 
- The type alias gets it's own .yml page. It'd be short, but look consistent.
- The type alias gets a section in the <package>.yml file, like a namespace-level function. 

I don't have a strong preference, as long as the UID cross-linking experience works.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-documenter` version? |  7.12.14 |
| Operating system? | Windows|
| Documentation target?  | DocFX (YAML) |
| Would you consider contributing a PR? | Yes  |
| TypeScript compiler version? |  7.12.14 |
| Node.js version (`node -v`)? | 12.16.1 |
