### ISSUE TITLE
[rush] Suggestion: rush "complex CI workflow" tool and/or example

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/rushstack#3838]
## Summary

In a large Rush monorepo that produces many types of apps, your CI workflow may have several jobs to do besides just running "rush build". Specifically there's two interesting jobs Rush can help with:

1. Kick off a _matrix build_ of all jobs matching a given criteria that were modified in this build (pull request).
2. Kick off specific additional jobs only if a certain project(s) were modified in this build (pull request).

In our monorepo, we've developed a somewhat generic way to represent this concept in CI, and it might be useful to other companies as well.

## Details

We have an internal project in our monorepo called `rush-changeset`. The only job of this project is to run `rush list --impacted-by git:${base_ref} --json`, and then "invert" the results to form a structure like this:

```json
{
  "impacted": {
    "projects": ["a", "b", "c", "d", "e"],
    "tags": {
      "tagA": ["b", "c"],
      "tagB": [],
      "tagC": [],
      "tagD": ["e"] 
    }
  }
}
```

(In English, this structure states: "this pull request impacts projects a, b, c, d, and e; it doesn't impact any tagB or tagC projects, but it does impact tagA projects b and c and tagD project e".)

In our GitHub Actions CI workflow, the `changeset` job kicks off in parallel with our main `build` job, and usually completes in about ~45 seconds (clone, install rush, run tool).

Then a whole series of other team-defined workflows can use the output in the JSON structure above...

### Matrix jobs

Consider a monorepo which contains many projects containing Terraform infrastructure, and on a pull request build, you want to deploy "PR previews" of each project that the PR impacts. This looks something like this:

```yaml
  deploy-infra-pr:
    needs: changeset
    if: always() && needs.changeset.result == 'success'
    strategy:
      matrix:
        project: ${{ fromJSON(needs.changeset.outputs.changeset).impacted.tags.terraform }}
    steps:
      - run: echo "Deploying infrastructure for ${{ matrix.project }}"
```

Alternately, consider a TypeScript project with an expensive binary wrapper (a React Native, or XBox UWP build, for example). If and only if a pull request impacts this project, you'll take the additional step of building the binary output to confirm the build still works (potentially running on a more expensive runner, like a Windows or MacOS GitHub runner).

```yaml
build-dynamite-binaries:
  needs: changeset
  if: always() && contains(fromJSON(needs.changeset.outputs.changeset).impacted.projects, '@acme/dynamite')
  steps:
    - run: echo "Building @acme/dynamite binaries"
```

### So what?

This particular JSON structure might be too specific to our needs; it's likely each maintainer needs something slightly different. But the overall strategy and then the GitHub Actions job examples could be useful in some kind of Rush cookbook.
