### ISSUE TITLE
[rush] Rush is not compatible with pnpm v8 due to lockfile v6 format

### ISSUE THREAD

**Issue by koen-dev** [microsoft/rushstack#4033]
## Summary
When posting this [PNPM just released v8.0.0](https://github.com/pnpm/pnpm/releases/tag/v8.0.0) which introduces a major upgrade for the lockfile format. This format isn't compatible with a check that Rush executes after a `rush install`. The following error occurs after `rush install`:
```
ERROR: version.includes is not a function
```

## Repro steps

1. Upgrade PNPM in any Rush repo from v6 or v7 to v8 by changing the setting `pnpmVersion` in `rush.json`.
2. Delete `pnpm-lock.yaml` in `common/config/rush`
3. Run `rush update --full --purge`

_[Above mentioned steps are following the instructions from the Rush docs.](https://rushjs.io/pages/maintainer/package_managers/#specifying-your-package-manager)_

  **Expected result:** 
`rush install` succeeds and new `pnpm-lock.yaml` is created.

  **Actual result:** 
`rush install` fails with the following message: `ERROR: version.includes is not a function`. However the lock file is created and looks valid.

## Details

This looks to be related to the following line:
https://github.com/microsoft/rushstack/blob/2f3aca6ae5620b3d6b62f281a317133505defee2/libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts#L527

Due to the new format of the lockfile the dependencies aren't split like this anymore:
```yaml
'@types/uuid': 8.3.4
axios: 0.21.4
date-fns: 2.29.3
```

The new format is:
```yaml
'@babel/core':
  specifier: ^7.21.0
  version: 7.21.0
'@babel/plugin-proposal-dynamic-import':
  specifier: ^7.18.6
  version: 7.18.6(@babel/core@7.21.0)
```

Let me also state that this is expected to not be compatible as it was just released and the Rush team needs time to support the newly released pnpm v8.
